### PR TITLE
remove "Administrator Interface" page

### PR DESCRIPTION
**Pull request by wwarner-salesforce**
This page describes a past version of the interface with many
obsolete screenshots. This info is now replaced by the newer
interface and other pages describing specific tasks.

### CODE REVIEW

**Comment by wwarner-salesforce** [comment]
@jdeoliveira I think this page was added in workshops to reduce customer confusion about the admin interface, and we intended to delete it before GA. I think now is a great time to delete it. The admin interface is better and completely different now. We explain how to use it on pages that describe how to perform specific tasks, which is better than having a separate page for just an interface tour.

Just discussed deleting this page with Paige Valkyrie and Meeta, and none of us have any objections.

**Review by jdeoliveira — DISMISSED** [review]
Agree on removing it - but let's add one screenshot on the main `operate.adoc` page explaining (in this order):
1. that in this UI is where all the topics in the operate section are done
2. how to get to it from the App Launcher (in case the user gets lost in the salesforce UI)
Thanks!

**Comment by wwarner-salesforce** [comment]
Good idea! Made those changes.

**Review by paigehargrave — APPROVED** [review]

**Comment by paigehargrave** [comment]
LGTM

**Pull request merged**
