### PR TITLE
DOCS-11263

### PR DESCRIPTION
**Pull request by Rodgers-Glenn**
https://www.mulesoft.org/jira/browse/DOCS-11263#

Updated API catalog section to explain that ACM search is not the same as API catalog.

### CODE REVIEW

**Review by wwarner-salesforce — DISMISSED** [review]

**Review by danvhenry — CHANGES_REQUESTED** [review]
I think it needs to read more as if we're highlighting the extended capability of the ACM search box. So, something like:

"Whilst the API Catalog search is for API's and API Groups, the <<acm-search-box>> component offers advanced search capabilities, to search all assets in your API Community."

Thoughts?

**Review by wwarner-salesforce — DISMISSED** [review]

**Comment by wwarner-salesforce** [comment]
Good ideas, Dan! Please check this version and tell us what you think.

**Review by danvhenry — DISMISSED** [review]
Looks good

**Review by kbostrom — APPROVED** [review]
CE

**Review by wwarner-salesforce — APPROVED** [review]

**Pull request merged**
