### PR TITLE
Branding & Customization- from Jesus' Google doc

### PR DESCRIPTION
**Pull request by wwarner-salesforce**

### CODE REVIEW

**Comment by wwarner-salesforce** [comment]
Found some missing items and added them. Please review and merge, or let me know if the items needed to be removed and I just didn't get the message.

**Comment by paigehargrave** [comment]
I included all those updates except for the Rick text editor text. That wasn't included in the sample video, so I left it out.

**Comment by wwarner-salesforce** [comment]
There was a Branding and Customization page on the beta site, and Jesus copied that into the Google doc "ACM docs review 7/5", made comments there, and then we created and merged PR 28, which also had a few comments. The current beta site page matches PR 28.

Google doc: https://docs.google.com/document/d/1CD8r_osXJwpeGT9uJRiCXEPNyqr8BRFyjaWR5TDJlvE/

PR 28: https://github.com/mulesoft/docs-api-community-manager/pull/28

Beta site page: https://beta.docs.stgx.mulesoft.com/beta-api-community-manager/api-community-manager/branding-and-customization

This PR 29 includes a few changes, so I'll go through each one.

1) First mention of "ACM" spelled out as "API Community Manager (ACM)", per Jesus comment in Google doc. PR 28 has "ACM" on line 9, and I think when we merged PR 28 the question was still being discussed in the Google doc with no decision to change anything.

2) "Theme Navigation Menu" changed to "Navigation Menu" to match the Google doc. PR 28 still has "Theme Navigation Menu" on line 25. This section of the docs was much improved by a rewrite you did to make it more brief and clear, and this small change was probably left out in the process. I think "Navigation Menu" is more correct, clear, and useful to customers, but "Theme Navigation Menu" could also work. Which do you think is best?

3) Note that on the Navigation Menu, "*Home* is always present and always the first item." This was on the previous page and is in the Google doc, with no comments to remove it in the Google doc or in PR 28. It was removed on line 40 of PR 28, as part of some text that was being moved around, and was not re-added anywhere in PR 28. I think it's useful to customers as they're working with the Navigation Menu and is better to keep, but we could omit the note. Which do you think is best?

4) Note that the rich text editor exists, and contrast the WSYWIG rich text editor and the source editing of the HTML editor. This was not on the previous site, and Jesus added it in the Google doc. There were no comments in the Google doc or PR 28 to take it out, and it wasn't added in PR 28. My impulse is that even if the video didn't take the time to cover it, it's better to follow the Google doc and leave it in, but we could take it out to match the video and make the file more brief. Which do you think would be best?

**Comment by paigehargrave** [comment]
Ah - OK - good catches! I was trying to keep things succinct. Changes work for me - I made one small syntax fix.

**Comment by wwarner-salesforce** [comment]
Great-- that looks perfect!

**Review by paigehargrave — APPROVED** [review]

**Pull request merged**
