### PR TITLE
Configure ACM

### PR DESCRIPTION
**Pull request by wwarner-salesforce**
Missing close quote in example.

### CODE REVIEW

**Review by paigehargrave — APPROVED** [review]

**Comment by wwarner-salesforce** [comment]
Much better-- thank you Paige!

**Comment by wwarner-salesforce** [comment]
Fran Escalada also suggested changing `'Authorization: Bearer token'` to `'Authorization: Bearer [YourToken]'`. Jesus says he's discussed changes to the example with Fran and will contact me about it.

**Comment by wwarner-salesforce** [comment]
Nicolas Battiato helped me fix the test instance configuration by updating the credentials. He said each instance of `/accounts/oauth2/` in the URLs should now be `/accounts/api/v2/oauth2/`. Jesus, please confirm this when you work on this PR.

**Comment by wwarner-salesforce** [comment]
Jesus confirmed the change to `/accounts/api/v2/oauth2/` in today's meeting.

**Comment by wwarner-salesforce** [comment]
Expanded "Create a connected app" section per Jesus in today's meeting, including adding info from https://docs.google.com/document/d/1EGcZSltz7MxmlAb2Bx0OVc4V2VEH2JGX4F5A8Iwq__0/edit#heading=h.tdkwqzyv3yb0 .

**Comment by wwarner-salesforce** [comment]
Added "Create Your Authentication Provider" section from @ferferrarazzo per https://www.mulesoft.org/jira/browse/AAP-1006 .

**Review by ferferrarazzo — APPROVED** [review]
It's ok for me.

**Comment by wwarner-salesforce** [comment]
Thank you Fernando!

@jdeoliveira please approve when you can, and I'll merge it.

**Review by jdeoliveira — CHANGES_REQUESTED** [review]
We need to MOVE the following sections to the top, under "Create and Authenticate the External Data Source": 
```
Create a Connected App
  Create a Connected App with the User Interface
  Create a Connected App with an API Call
Configure Authentication Provider (MERGE with Create Authentication Provider)
```

They should be at the beginning of the section - "Configure Authentication Provider" and "Create Authentication Provider" should be combined, I think they are more or less the same content, so let's keep it as "create".

After this section, it should come "Authorize and Authenticate Your External Data Source"

End result of this first section should be:
*Create and Authenticate the External Data Source*
```
Create a Connected App
  Create a Connected App with the User Interface
  Create a Connected App with an API Call
Create Your Authentication Provider
Authorize and Authenticate Your External Data Source
```

The setting up impersonation section should then start directly with 
```
Configure Salesforce as a SAML Identity Provider
Set Up Custom Attributes
Configure External Identity in Your Anypoint Organization
...
```

**Comment by wwarner-salesforce** [comment]
Thank you @jdeoliveira ! I reorganized the file to match your comment. Please review and approve if I got it right.

**Review by jdeoliveira — APPROVED** [review]

**Pull request merged**
